// ====================
// WORDS CACHE
// Backup Dictionary for Offline Use
// ====================

window.backupDictionary = {
    english: [
        // Common 3-letter words (200+)
        'the','and','for','are','but','not','you','all','any','can','had','her',
        'was','one','our','out','day','get','has','him','his','how','man','new',
        'now','old','see','two','way','who','boy','did','its','let','put','say',
        'she','too','use','may','way','air','bag','car','dog','egg','fox','god',
        'hat','ice','jam','key','leg','mom','not','owl','pig','que','rat','sun',
        'toy','use','van','win','yes','zoo','act','bad','cup','dig','eat','fly',
        'goo','hop','ink','jog','kit','log','mud','nap','opt','pet','quit','run',
        'sit','tap','urn','vet','wet','yap','zip','ace','bee','cry','dry','eye',
        'fry','gym','hay','ice','joy','kid','lay','mix','nay','oak','pay','que',
        'ray','sea','try','use','vie','why','yay','zoo','arm','box','cat','die',
        'ear','fan','gun','hit','ion','jaw','keg','lip','mop','net','own','pie',
        'rag','saw','tin','ump','via','wow','yak','axe','bye','cow','dew','elf',
        'fog','gem','hog','ivy','jot','kin','log','mat','nit','orb','peg','rug',
        'sip','tan','urn','vow','wax','yen','ado','boo','coy','dun','eel','fig',
        'gab','hug','irk','jab','ken','lad','mug','nag','oaf','pad','rag','sag',
        'tab','urn','vat','wig','yap','arc','bud','cub','dad','ebb','flu','gag',
        
        // 4-letter words (300+)
        'that','with','have','this','will','your','from','they','know','want',
        'been','good','much','some','time','very','when','come','here','make',
        'like','long','many','more','only','over','such','take','than','them',
        'well','were','what','which','their','said','each','about','how','will',
        'then','these','some','her','would','make','like','him','into','time',
        'has','look','two','more','write','go','see','number','no','way','could',
        'people','my','than','first','water','been','call','who','oil','its','now',
        'find','long','down','day','did','get','come','made','may','part','over',
        'new','sound','take','only','little','work','know','place','year','live',
        'me','back','give','most','very','after','thing','our','just','name','good',
        'sentence','man','think','say','great','where','help','through','much',
        'before','line','right','too','mean','old','any','same','tell','boy','follow',
        'came','want','show','also','around','form','three','small','set','put','end',
        'does','another','well','large','must','big','even','such','because','turn',
        'here','why','ask','went','men','read','need','land','different','home','us',
        'move','try','kind','hand','picture','again','change','off','play','spell',
        'air','away','animal','house','point','page','letter','mother','answer','found',
        'study','still','learn','should','America','world','high','every','near','add',
        'food','between','own','below','country','plant','last','school','father','keep',
        'tree','never','start','city','earth','eye','light','thought','head','under',
        'story','saw','left','dont','few','while','along','might','close','something',
        'seem','next','hard','open','example','begin','life','always','those','both',
        'paper','together','got','group','often','run','important','until','children',
        'side','feet','car','mile','night','walk','white','sea','began','grow','took',
        'river','four','carry','state','once','book','hear','stop','without','second',
        'late','miss','idea','enough','eat','face','watch','far','Indian','really',
        'almost','let','above','girl','sometimes','mountain','cut','young','talk','soon',
        'list','song','being','leave','family','its','always','both','color','add',
        'been','change','almost','above','below','form','large','small','high','low',
        
        // 5-8 letter common words (500+)
        'about','after','again','below','could','every','first','found','great','house',
        'large','learn','never','other','place','plant','point','right','small','sound',
        'spell','still','study','their','there','these','thing','think','three','water',
        'where','which','world','would','write','above','again','along','begin','being',
        'below','bring','build','catch','carry','cause','check','class','clear','close',
        'color','could','cover','cross','dance','drawn','dream','drink','drive','early',
        'earth','eight','enough','enter','every','field','fight','final','first','floor',
        'force','front','glass','great','green','group','guess','happy','heart','heavy',
        'horse','hotel','house','human','ideas','image','issue','joint','jumps','known',
        'later','laugh','learn','light','local','lower','major','maybe','means','metal',
        'might','model','money','month','mouth','music','needs','never','night','noise',
        'north','occur','ocean','often','order','other','owner','paper','party','peace',
        'phase','phone','piece','place','plane','plant','point','pound','power','press',
        'price','pride','prime','print','prior','prize','proof','proud','prove','quick',
        'quiet','quite','radio','raise','range','rapid','ratio','reach','ready','refer',
        'right','river','round','route','royal','rural','scale','scene','score','sense',
        'serve','seven','shall','shape','share','sharp','sheet','shift','shirt','shock',
        'shoot','short','shown','sight','since','sixth','skill','sleep','slide','small',
        'smart','smile','smoke','solid','solve','sorry','sound','south','space','speak',
        'speed','spend','spoke','sport','staff','stage','stand','start','state','steal',
        'steel','stick','still','stock','stone','stood','store','storm','story','strip',
        'stuck','study','stuff','style','sugar','suite','super','sweet','table','taken',
        'taste','taxes','teach','teeth','tells','thank','theft','their','theme','there',
        'these','thick','thing','think','third','those','three','threw','throw','tight',
        'times','tired','title','today','token','tonne','topic','total','touch','tough',
        'tower','track','trade','train','treat','trend','trial','tried','tries','truck',
        'truly','trust','truth','twice','uncle','under','union','unity','until','upper',
        'urban','usage','usual','valid','value','video','virus','visit','vital','voice',
        'wages','waste','watch','water','wheel','where','which','while','white','whole',
        'whose','woman','women','works','world','worry','worse','worst','worth','would',
        'wound','write','wrong','youth','yours','young','yield','yards','xenon','years'
    ],
    
    malay: [
        // Kata umum 3 huruf (150+)
        'ada','air','api','aku','ibu','dia','kita','kamu','itu','ini','sia','apa',
        'bagi','dua','tiga','empat','lima','enam','tujuh','lapan','sembilan','sepuluh',
        'batu','rumah','jalan','kayu','besi','emas','kaca','awan','hujan','angin',
        'bumi','bulan','matahari','bintang','dunia','negeri','bandar','kampung',
        'sungai','laut','gunung','hutan','sawah','kebun','taman','pasar','kedai',
        'sekolah','masjid','gereja','kuil','hospital','polis','bomba','kereta','bas',
        'keretapi','kapal','pesawat','roda','pintu','tingkap','atap','dinding','lantai',
        'siling','meja','kerusi','katil','almari','peti','pinggan','mangkuk','gelas',
        'cawan','sudu','garpu','pisau','periuk','kuali','ketuhar','peti','ais','minyak',
        'garam','gula','tepung','beras','sagu','jagung','ubi','keladi','pisang',
        'rambutan','durian','mangga','nanas','tembikai','betik','limau','oren','epal',
        'anggur','pir','makan','minum','tidur','bangun','mandi','basuh','cuci','sapu',
        'masak','goreng','rebus','kukus','panggang','bakar','salai','tumbuk','kisar',
        'hiris','potong','belah','cincang','parut','perah','ramas','kacau','adun','uli',
        'canai','uli','tekan','tarik','tolak','angkat','bawa','angkat','letak','simpan',
        'ambil','beri','kirim','hantar','terima','beli','jual','bayar','hutang','piutang',
        'untung','rugi','modal','harga','murah','mahal','percuma','diskaun','promosi',
        
        // Kata 4-5 huruf (200+)
        'makan','minum','tidur','bangun','mandi','basuh','cuci','sapu','masak','goreng',
        'rebus','kukus','panggang','bakar','salai','tumbuk','kisar','hiris','potong',
        'belah','cincang','parut','perah','ramas','kacau','adun','uli','canai','tekan',
        'tarik','tolak','angkat','bawa','letak','simpan','ambil','beri','kirim','hantar',
        'terima','beli','jual','bayar','hutang','piutang','untung','rugi','modal','harga',
        'murah','mahal','percuma','diskaun','promosi','iklan','jualan','belian','stok',
        'inventori','gudang','kedai','gerai','pasar','pameran','ekspo','festival','karnival',
        'pertandingan','kejohanan','liga','piala','pingat','hadiah','ganjaran','bonus',
        'komisen','dividen','faedah','bunga','pokok','akar','batang','dahan','ranting',
        'daun','bunga','buah','biji','benih','tunas','pucuk','kudup','putik','layu',
        'gugur','busuk','rosak','reput','segar','ranum','masak','mentah','keras','lembut',
        'lembik','rangup','garing','renyah','lemak','manis','masin','masam','pahit','pedas',
        'kelat','tawar','hamis','anyir','hanyir','wangi','harum','busuk','hambar',
        
        // Kata 6-8 huruf (150+)
        'makanan','minuman','pakaian','perabot','perkakas','peralatan','kenderaan',
        'bangunan','struktur','infrastruktur','kemudahan','perkhidmatan','perusahaan',
        'industri','perdagangan','perniagaan','perkapalan','penerbangan','pengangkutan',
        'komunikasi','telekomunikasi','penyiaran','penerbitan','percetakan','pengiklanan',
        'pemasaran','pengedaran','pengagihan','pengimportan','pengeksportan','pengeluaran',
        'pembuatan','pembinaan','pemasangan','pembaikan','penyelenggaraan','pengubahsuaian',
        'peningkatan','perkembangan','pertumbuhan','perluasan','pengembangan','perbesaran',
        'pengecilan','pengurangan','penambahan','percampuran','pergabungan','percantuman',
        'pemisahan','pembahagian','pengasingan','pengelasan','pengkategorian','penjurusan',
        'pengkhususan','kepakaran','keahlian','kemahiran','kebolehan','keupayaan','kekuatan',
        'kelemahan','kekurangan','kelebihan','keistimewaan','keunikan','kebiasaan','kelaziman',
        'bermain','belajar','bekerja','bercakap','berjalan','berlari','berenang','terbang',
        'menyanyi','menari','melukis','menggambar','membaca','menulis','mengira','menghitung',
        'mengukur','menimbang','menganalisis','menyelidik','mengkaji','mempelajari','mengajar',
        'melatih','membimbing','memimpin','mengurus','mengelola','mengendali','mengawal',
        'mengawasi','memantau','menyelia','pemerintah','pengurusan','pentadbiran','kementerian',
        'jabatan','bahagian','unit','seksyen','sektor','industri','perusahaan','syarikat',
        'perbadanan','korporat','organisasi','pertubuhan','persatuan','kelab','komuniti',
        'masyarakat','penduduk','warganegara','rakyat','bangsa','kaum','etnik','suku','puak',
        'kumpulan','kategori','jenis','bentuk','corak','model','contoh','sample','spesimen',
        'prototaip','versi','edisi','siri','kumpulan','set','koleksi','senarai','jadual',
        'jadual','kalendar','timetable','schedule','rancangan','plan','strategi','taktik',
        'kaedah','method','teknik','prosedur','process','proses','langkah','step','tahap',
        'peringkat','level','aras','standard','piawaian','kriteria','syarat','keperluan',
        'requirements','spesifikasi','specification','detail','butiran','maklumat','information',
        'data','fakta','fact','realiti','reality','kenyataan','statement','keterangan',
        'explanation','penjelasan','clarification','penjelasan','penerangan','description',
        'definisi','definition','maksud','meaning','erti','sense','logik','logic','rasional',
        'rational','reasonable','munasabah','acceptable','diterima','approved','disahkan',
        'verified','confirmed','sah','valid','benar','true','betul','correct','tepat','accurate',
        'precise','jitu','exact','spesifik','specific','umum','general','common','biasa','ordinary',
        'luar','outside','dalam','inside','atas','above','bawah','below','depan','front',
        'belakang','back','kanan','right','kiri','left','tengah','middle','pusat','center',
        'tepi','edge','sisi','side','sudut','corner','penjuru','junction','persimpangan'
    ]
};

console.log('Backup dictionary loaded:', 
    'English:', window.backupDictionary.english.length, 'words |',
    'Malay:', window.backupDictionary.malay.length, 'words'
);